# Generated by Django 3.1.1 on 2020-09-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('place_desc', models.CharField(max_length=300)),
                ('contrib_date', models.DateField()),
            ],
        ),
    ]
