# Generated by Django 3.1.1 on 2020-10-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='places',
            name='image',
            field=models.ImageField(default='', upload_to='web/images'),
        ),
    ]
