# Generated by Django 3.1.1 on 2020-12-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201004_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_dist',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='places',
            name='place_state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
