# Generated by Django 3.1.1 on 2020-12-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201203_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_comp_addre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='place_name',
            field=models.CharField(max_length=20),
        ),
    ]
